### ISSUE TITLE
Why does the regex output often have a •?

### ISSUE THREAD

**Issue by clache547** [rindPHI/grammar2regex#1]
In the example regex output: ((["-" .. "."] | ["0" .. "9"] | ["A" .. "Z"] | "_" | ["a" .. "z"])* • (["-" .. "."] | ["0" .. "9"] | ["A" .. "Z"] | "_" | ["a" .. "z"]))
there seems to be a • symbol when the initial grammar to be converted does not contain such a symbol. This does not seem to reflect proper regex. Can this be explained?

**Comment by rindPHI** [comment]
This is simply the concatenation operator :) It's part of the reflex syntax I chose. You can also have the output as a Z3 regex object if you prefer.

**Comment by clache547** [comment]
I see. If I would like to use an output that is a syntactically correct regex string, would removing the concatenation operator suffice?
